### ISSUE TITLE
EACにて利用しようとした際に「No Handshake!」というエラーが表示される

### ISSUE THREAD

**Issue by yanoshi** [KeiNakamura/EacToGracenote#1]
以前より非常に重宝しております。

近頃、デモサイトに記載されているCDDB( `http://gncddb.azurewebsites.net/cddb.svc/cddb` )をEACにて利用しようとした際に `No Handshake!` というエラーが表示されます。(EAC v1.1及びv1.3にて確認。Mp3tagから叩いた際もエラーメッセージが表示されます)

https://gyazo.com/136956d6bfcb7491646a818806b95c6b

これは既知の不具合でしょうか？

**Comment by KeiNakamura** [comment]
ご連絡ありがとうございます。
こちらでも事象再現しました。

- 事象
全てのリクエストに対して `No Handshake!` のエラーが返される。

- 原因
Gracenote API キーの更新が漏れており有効期限切れとなったため。
キーの有効期限は1年間（正確には未検証）

- 対応
Gracenoteアプリを再作成し、新しいキーを登録し復旧を確認。

お手数ですが再度お試し頂けますでしょうか。

**Comment by yanoshi** [comment]
ありがとうございます！無事こちらでも動作いたしました！
